services:
  backend:
    build: ./backend
    container_name: major-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "4518:4518"
    
  frontend:
    build: ./frontend
    container_name: major-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend